# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9DXQZ5NUeJqMq8YaqFS1dz_pds2pnmn
"""

from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from tensorflow.keras.models import load_model
import numpy as np
from PIL import Image
import io

app = FastAPI()

# Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "https://your-vercel-app.vercel.app",  # Update this if deployed elsewhere
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load your trained model
model = load_model(r'C:\Users\JOHN\Desktop\server\model\railway_fault_detector_vgg16.h5')

@app.get("/")
async def root():
    return {"message": "Railway Fault Detector API is running 🚂"}

@app.post("/predict/")
async def predict(file: UploadFile = File(...)):
    try:
        contents = await file.read()
        image = Image.open(io.BytesIO(contents)).convert('RGB').resize((224, 224))
        image_array = np.array(image) / 255.0
        image_array = np.expand_dims(image_array, axis=0)

        prediction = model.predict(image_array)[0]

        # Assuming class 0 = faulty, class 1 = safe
        faulty_prob = float(prediction[0])
        safe_prob = float(prediction[1])

        return {
            "safe_probability": safe_prob,
            "faulty_probability": faulty_prob,
            "status": "Fault Detected! ❌" if faulty_prob > 0.5 else "Track is Safe ✅"
        }

    except Exception as e:
        return {"error": str(e), "message": "Invalid image or server error."}