# -*- coding: utf-8 -*-
"""test_model_loading.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9qUbnhOJUR5y2vRv2G3esFzy_0Xb620
"""

from tensorflow.keras.models import load_model
import numpy as np

# Load your fine-tuned VGG16 model
model = load_model(r'C:\Users\JOHN\Desktop\server\model\railway_fault_detector_vgg16.h5')

# Create a dummy input (random image) with correct dimensions
test_image = np.random.rand(1, 224, 224, 3)

# Make a prediction
prediction = model.predict(test_image)

print("✅ Model loaded successfully!")
print("Prediction output:", prediction)